# FROM node:alpine

# WORKDIR '/app'

# COPY ./package.json ./

# RUN npm install

# RUN npm config set unsafe-perm true

# COPY . .

# CMD ["npm", "run", "start"]

FROM node:alpine

USER node 

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]
