sudo: required
services:
  - docker

before_install:
  - docker build -t rnk487/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rnk487/react-test npm test

after_success:
  - docker build -t rnk487/multi-client ./client
  - docker build -t rnk487/multi-nginx ./nginx
  - docker build -t rnk487/multi-server ./server
  - docker build -t rnk487/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to DockerHub
  - docker push rnk487/multi-client
  - docker push rnk487/multi-nginx
  - docker push rnk487/multi-server
  - docker push rnk487/multi-worker

deploy:
  provider: elsaticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY